### ISSUE TITLE
Your plugin cant correctly locate file

### ISSUE THREAD

**Issue by palandovalex** [RimuhRimu/runthis.nvim#18]
My pwd whas
`/home/<username>/<project_name>`
I openend file
`/home/<username>/<project_name>/code/app.py`

Output was:
```
Running { /home/lexsilentium/scrypton/.venv/bin/python app.py } on file -> 'app.py'
-
/home/<username>/<project_name>/.venv/bin/python: can't open file '/home/<username>/<project_name>/app.py': [Errno 2] No such file or directory
```

so, your plugin didnt get the relative path of file, and used his name.

**Comment by RimuhRimu** [comment]
Hi there, thanks for reporting this, update the plugin and tell me if you have any troubles, now it should work as expected, I'm adding some additional tests to avoid these problems.
