### ISSUE TITLE
Autorun if only 1 buffer opened

### ISSUE THREAD

**Issue by palandovalex** [RimuhRimu/runthis.nvim#8]
i think that when only 1 buffer is opened - it must be obvios to chouse, what file to run)

And also, you need to remind your self, that 1 opened buffer at 1 time - is tipical situation

**Comment by RimuhRimu** [comment]
You are right, I wasn't really programming much lately so I didn't realize this before, thanks for your comment, it should run the current buffer if there is only one open.
